### ISSUE TITLE
Not working for me.

### ISSUE THREAD

**Issue by illaniit** [Kyoro93/stremio-install-ubuntu-22.04#1]
I download it and i've done everything but when I execute the app isn't working because it doesn't open.

**Comment by Kyoro93** [comment]
What's your operational system?
And if possible, can you share with me the error that appears on your console?

**Comment by illaniit** [comment]
Ubuntu 22.04  the latest version, I don't have any error on the console because the script works and I have the app downloaded the problem is that it doesn't charge the app

**Comment by Kyoro93** [comment]
When you opens the terminal and runs the command below, what's the output?
"stremio"

**Comment by illaniit** [comment]
![imagen](https://user-images.githubusercontent.com/86691041/178298660-e070070a-1efe-4a71-bd71-5caf1110cae0.png)

This is the message that I get when I do the sudo ./etc...

**Comment by illaniit** [comment]
![imagen](https://user-images.githubusercontent.com/86691041/178298875-1d29cef6-f652-4005-8920-f5ba4406ecba.png)

But as you can see I have it downladed so I press in the icon but nothing happens and the app does not open.

**Comment by Kyoro93** [comment]
I see the problem, the libssl file got a new version: 1.6
Just fixed it on the shell script, just download it again and run it

**Comment by illaniit** [comment]
OK!! thankss I'll try

**Comment by illaniit** [comment]
YESSSSS now it works! thanks for all man, you're great! I've been fighting a week to install stremio in my computer. You're owesome!

**Comment by Kyoro93** [comment]
I'm glad that this helped, enjoy watching your favorite series and movies :)
